### ISSUE TITLE
Maintenance of phpcrawl

### ISSUE THREAD

**Issue by jarodium** [mmerian/phpcrawl#9]
Hello

Is phpcrawl being maintained by the author?
I have tried to reach him by e-mail regarding the class but no success...

**Comment by mmerian** [comment]
Hi,
I don't know if it is still maintained. My first objective with this repo was to provide a composer-installable library, and only keeping upstream code.

**Comment by praad** [comment]
Hello I'm interested in developing this crawler. I also tired to reach him but his email is not available anymore. I have couple of ideas to implement. Is there any active code somewhere else?

**Comment by mmerian** [comment]
Hi
As far as i know, there is active code on this project somewhere else. If you want to implement features / fix bugs, feel free to fork this repo and make pull requests.

Regards,

**Comment by praad** [comment]
Ok thanks
